### ISSUE TITLE
Configure Analytics

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/sw-flow-trends#110]
- [x] USA Analytics

- [x] WIM Google analytics

- [x] Add to WMA analytics

**Comment by HansVraga** [comment]
This will wait until we decide where the production URL will be

**Comment by HansVraga** [comment]
Production URL set to: iwaas.wim.usgs.gov/sw-flow-trends

**Comment by HansVraga** [comment]
Can we track what filter combinations put in? @lprivette

**Comment by njestes** [comment]
Do we need to set up the production URL before we can set up all the analytics? @lprivette @HansVraga

**Comment by lprivette** [comment]
Hewo.

**USA Analytics**: nawqatrends.wim.usgs.gov is registered and recording with that site. Is this what it should be or do I need to add another? https://analytics.usa.gov/interior/data/ > "Visits to all domains over 30 days" (CSV button)

**WIM GA**: does not need a prod url (data is associated with ID in the index.html and sent to GA) and is already setup and running with the normal site data and some custom clicks. It is using an outdated version of GA but that's not a huge deal. The title of the GA account is 'NAWQA SW Trends', is that the same or is this a different app? @njestes . @HansVraga Yes we can probably track what filters are selected, I'll get it setup and probably update the GA version we're using as well. 


**WMA analytics**: Does 'WMA analytics' mean the USGS-VIZLAB/ internal-analytics? just want to confirm on that.

**Comment by HansVraga** [comment]
We have several nawqa trends apps.
Yes, data vis group the same as WMA analytics

**Comment by njestes** [comment]
@lprivette time for this ☝️ sometime in the next couple weeks?

**Comment by lprivette** [comment]
Complete upon these PR merges: 
https://github.com/USGS-WiM/NSS/pull/473/files (USA Analtyics)
https://github.com/USGS-VIZLAB/internal-analytics/pull/251 (WMA Analytics)

**Comment by jprokopec** [comment]
https://lookerstudio.google.com/reporting/3f80c1e7-8006-49e4-adb7-c8159bb367d3/page/4VDGB
