### ISSUE TITLE
Symbol colors

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/sw-flow-trends#115]
Feedback from cooperator:

>There is concern the red and black colors for the trend symbols may not be distinguishable to color-blind people, though there is still the different directions indicated by the arrows

>Regarding color scheme of the symbols: We’ve commonly used blue for increases (more water over time) and brown for decreases (less water over time) when generating figures (like the one above) as they are perhaps more intuitive for some people to communicate 'wetting' and 'drying' over time. However, if we use those colors, the Q2 nDays, Scaled Deficit,  Last JD, JD Difference, and ZeroQ nDays symbol colors would need to be reversed because a decreases over time actually indicates wetter conditions over time. This is largely why I didn't propose this to begin with - in an effort to keep the application simple for it's first version. If it's easy to implement, we'd need to explain the colors and why they are 'reversed' for certain variables in the FAQ.

**Comment by njestes** [comment]
Mitch took a look under the impression that it was ultimately up to us to make the color decision, so we're leaving it as is. Will open it back up if they change their minds and insist that we should make the change.
