### ISSUE TITLE
Missing symbols for 7 day low and annual

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/sw-flow-trends#119]
(Potentially related to #112 )
Feedback from cooperator:

> Regarding symbology on the map for 7-day low flows and annual mean: there are a few instances of trends with zero slope but there are no symbols for no trend (open circle) appearing on the maps. The figure below from the article shows some grey circles (mostly in the middle of the U.S.) indicating instances of no trend for 7-day low flows. I have confirmed the data release data files do have instances of zero trend so it may be a simple matter of checking the trend magnitude field for zero and changing the symbol to reflect it.

![image](https://user-images.githubusercontent.com/12058013/97121280-162b6380-16eb-11eb-989f-5ce1965af030.png)

**Comment by njestes** [comment]
Think I've addressed this. Robert Dudley will check the results.
