### ISSUE TITLE
Add UptimeBot Monitoring 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/sw-flow-trends#146]
Add the application and the map services to UptimeBot.

(FGDC checker no longer appears to be accessible)

**Comment by jprokopec** [comment]
Close when you have checked this has been added.

**Comment by njestes** [comment]
app: https://dashboard.uptimerobot.com/monitors/789079019

service: https://dashboard.uptimerobot.com/monitors/797979025
