### ISSUE TITLE
Trend Periods

### ISSUE THREAD

**Issue by jprokopec** [USGS-WiM/sw-flow-trends#160]
Based on meeting notes [10/09/24](https://doimspp.sharepoint.com/:w:/r/sites/GS-UMidWIM/_layouts/15/Doc.aspx?sourcedoc=%7B7DC034BF-44B5-4821-9A2A-4933EE808969%7D&file=FY2025%20IWAAS%20Trends%20Meeting%20Notes.docx&action=default&mobileredirect=true
) update the Trend Periods to these 4

- Longest period of record 
- 1980-2020 
- 1990-2020 
- 2000-2020

**Comment by ghost** [comment]
Closing because this repo is already migrated to GitLab.
