### ISSUE TITLE
create new explanation (reverse order of symbols top to bottom)

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/sw-flow-trends#22]
Going to see if that's possible in the mxd. If not, will want an static image like the one in sw trends

**Comment by njestes** [comment]
@mitchas Giving this to you. Need a static image for the explanation like the one you did for sw trends. Here's the order as requested from our cooperator:

Explanation looks good but I suggest the order from top to bottom to be: Sig trend up, non-sig trend up, no trend, non-sig trend down, sig trend down.

**Comment by njestes** [comment]
@mitchas you can wait to tackle this until I've completed #23

**Comment by HansVraga** [comment]
![image](https://user-images.githubusercontent.com/12058013/79917457-2424c280-83f0-11ea-8621-6f3c858e524d.png)

Like this
