### ISSUE TITLE
Updates to User Guide, screen shots

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/sw-flow-trends#24]
- [ ] The example screen grab in the "Map Interface User Guide" should match the explanation
- [ ] Also updates need to be made to the "Map Selection Options" under the "Map Interface User Guide" such as removing "Selecting a consituent" or maybe changing that to a "Selecting a Model" section (for LTP, AR1, INDE). Trend type needs removal, and TRend Periods screen grab needs to match our time periods.

**Comment by HansVraga** [comment]
Duplicate to #50
