### ISSUE TITLE
Available Trends dropdown Menu feedback

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/sw-flow-trends#27]
- [x] Address JD selections

- [x] Group items

Feedback from cooperator:

>JD last and JD first: It isn't immediately obvious to me what that  means -- I'd suggest a) spelling it out to something like Julian Date First or Last Q2.  Maybe Rob can suggest something a little more elegant (and accurate, since it's dropping *below* Q2 that triggers it)

>consider grouping items in the drop down menu so that the user can clearly see which variables are low flows, mean flows, or high flows. There's really just the one mean flow var and the one peak flow variable though, with zero flows stuck in between at the moment.

**Comment by HansVraga** [comment]
#34 Describes how to address JD selections.

**Comment by njestes** [comment]
@HansVraga was that 'group items' comment from Julie? We may need further clarification on that.

**Comment by HansVraga** [comment]
Nick - yes it was. I think we can ask Rob/Julie for more clarification there next time we have a chat with them.

**Comment by njestes** [comment]
from Julie:

Some suggested headings:
-----------------
Low flows
     LowQ 1 Day
     LowQ 3 Day
     LowQ 7 Day
     Scaled Deficit
     nDays
     Last Julian date flow <= the Q threshold
     First Julian date flow >= the Q threshold
     JD Difference Q2
     Zero Q

Mean flows
    Mean Annual Q

Peak flows
     Instantaneous Annual Peak Flow

**Comment by esmyers** [comment]
I put these group headings in  so they will be in the next commit.  I will keep the issue open for the time being, because it wasn't clear if they had finalized their preferences yet.
