### ISSUE TITLE
User Guide Updates

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/sw-flow-trends#50]
We should take a look at the User Guide, which (at the time this issue is being opened) has a lot of holdover from the surface water quality trends application.

- [x] Update all images once we're confident we're done with styling changes 

- [x] Update text for "Opening a site" to describe this application's site pop-up

- [x] Update text for "Moving a site window" to include specifically clicking and dragging from the pop-up title

- [x] Update "Selecting a Constituent", "Selecting a Trend Type", and "Selecting a Trend Period" to Trend, Model, Trend period (to match this application

- [x] Will need to add a section about using the custom trend period

**Comment by mitchas** [comment]
Blank space added for using the custom trend period. We'll just need something written up for it now. Also maybe read through the ones that are already in.
